export enum USERS_BY_TIME_DATA {
  TODAY = 'TODAY',
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
}

export enum BY_SUBSCRIPTION_TYPE {
  USERS = 'USERS',
  ORDERS = 'ORDERS',
}

export enum DEVICES_BY_TIME_DATA {
  SEVEN_DAYS = 'SEVEN_DAYS',
  THIRTY_DAYS = 'THIRTY_DAYS',
  SIXTY_DAYS = 'SIXTY_DAYS',
}
